name: projectinfinity
favicon: null
layout_spectrum: 0
typography_spectrum: 0.48613
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7cfad'
    - '#395d9b'
    - '#4a77b2'
    - '#7e9fc0'
    - '#bbc9e3'
  brandStrength: 1
  lightness: 0.7424521
  saturation: 0.8659722
  rhythmicContrast: 0.651159
purpose: []
